spring:
  application:
    name: pagamentos-ms
  datasource:
    url: jdbc:h2:file:./data/pagamentos
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    enabled: true
server:
  port: 61325